### ISSUE TITLE
How to tell a speedseq output translocation (BND) is a balanced translocation or unbalanced?

### ISSUE THREAD

**Issue by crazyhottommy** [hall-lab/svtools#155]
Hi,

I have some speedseq output SV VCF files, how can I tell a BND is balanced or unbalanced translocation?

Thanks!
Tommy

**Comment by ernfrid** [comment]
Just talked this over with @cc2qe (Thanks Colby!). Our expectation is that you should get 1 variant per side of the translocation. Thus a balanced translocation would have 2 variants and thus 4 BND lines in the resulting VCF. The two variants would have support on opposite strands. An unbalanced translocation would have only one variant with strand support from one orientation only.

To distinguish the two in the current output, I think you would need to cluster your potential translocations by position and identify balanced translocations by examining those variants that are complementary in orientation and cluster together.

**Comment by fpbarthel** [comment]
Hi Dave,

This makes a lot of sense! We also see results like this in our data, great. However, sometimes it's hard to correctly make the distinction. Take these two examples in acute myeloid leukemia. Reciprocal PML-RARA translocations (with resulting fusion genes) are founder events in the promyelocytic (M3) variant of AML. In example 1 below, both the first and second breakpoints overlap between variant 1 and 2. In contrast, in example 2 only the first breakpoints overlap between variant 1 & 2, whereas the second breakpoint is ~70 nt apart. Wonder if you have some ideas on how to deal with this. We thought about extending the 'confidence interval' for all breakpoints in all samples to span 100 nt. But we're not sure how confident the confidence interval is, how it is defined and if this solution would break the whole idea of the predefined breakpoint limits?

Thanks!

###  Example 1
    Chr1	Start1		End1		Chr2	Start2		End2		Name	Score	Strand1	Strand2	Type
    chr15	74326283	74326298	chr17	38501756	38501776	5923	406.38	+		-		BND
    chr15	74326285	74326291	chr17	38501762	38501768	5924	579.25	-		+		BND

### Example 2
    Chr1	Start1		End1		Chr2	Start2		End2		Name	Score	Strand1	Strand2	Type
    chr15	74326319	74326336	chr17	38495969	38495983	5181	279.91	+		-		BND
    chr15	74326322	74326336	chr17	38496052	38496072	5182	313.89	-		+		BND

**Comment by cc2qe** [comment]
Hey Tommy and @fpbarthel,

Keep in mind that not all reciprocal translocations are balanced events. In fact, many are really complex breakpoints with concomitant deletions, duplications, or inversions at the breakpoints (see [Chiang et al. 2012](http://www.nature.com/ng/journal/v44/n4/abs/ng.2202.html)). Thus, while it's possible that the gap in Example 2 is due to a mistake in LUMPY's confidence interval, it is perhaps more likely that some sequence was deleted at the breakpoint of this translocation.

Your clustering leniency should depend on the nature of your experiment but I'd probably start by clustering events within 1 kb or so

--Colby

**Comment by fpbarthel** [comment]
Thanks Colby and Dave. How do you typically deal with breakpoints that span a long range? We find that > 80% of breakpoints have a span of ~20 nt, but a small fraction of breakpoints span > 100 nt and up to approximately 1kb. These wide breakpoints would interfere with breakpoint clustering, is it acceptable to drop breakpoints wider than say 100 nt?

**Comment by cc2qe** [comment]
It would be defensible to drop events with gaps > 100 bp, although keep in mind that this will exclude unbalanced translocations.

**Comment by fpbarthel** [comment]
Yes, that right. I actually meant the breakpoint confidence interval span. Typically (in >80% of sv's) the CI span is approx 20 nt, but there is a long tail of up to 1000 nt. Why are these CI's so wide for some SVs? Is it typical to drop these events with wide CI?

**Comment by cc2qe** [comment]
The CI reflects the evidence type. Paired-end evidence is less spatially precise than split-read evidence, so it results in a wider CI.

It is also possible for conflicting evidence to lengthen the CI, but we do not typically filter based on CI length since we generally trust LUMPY to probabilistically determine whether the evidence reflects a single or multiple variants.

**Comment by crazyhottommy** [comment]
Thanks, I have a much better understanding now.

**Comment by ernfrid** [comment]
Glad we could help!
