### ISSUE TITLE
work-flow

### ISSUE THREAD

**Issue by brentp** [hall-lab/svtools#199]
Hi, I am trying to use svtools lsort and lmerge to run lumpy -> svtyper across a large cohort without using the full svtools pipeline. My work-flow is:

1. lumpy in groups of $n
2. svtyper per sample
3. svtools lsort *sample.svtyper.vcf.gz | svtools lmerge > merged.vcf
4. svtype each sample for all sites in merged.vcf
5. combine/paste svtyped vcfs

Q1: Is this workflow supported? I am hitting some errors in lmerge.

Q2: does svtools need or use the sample columns from lumpy or can I reduce the output of lumpy with `cut -f 1-8` ?

**Comment by ernfrid** [comment]
Q1: I've never tried it this way, but after a quick look through the code, I think it should work. If you want to post what errors you are seeing in lmerge then I'll look into what the issue might be.

Q2: lsort and lmerge attempt to preserve the name of the samples where each SV was discovered using the SNAME info field. In addition, lsort removes sites where no sample has a variant. I would expect problems if you attempt to exclude the genotypes. In general, handling of VCFs where the format fields are missing is very poorly supported in svtools.

**Comment by brentp** [comment]
I'm getting:
```
Traceback (most recent call last):
File "/usr/local/bin/svtools", line 9, in <module>
load_entry_point('svtools==0.3.2', 'console_scripts', 'svtools')()
File "build/bdist.linux-x86_64/egg/svtools/cli.py", line 78, in main
File "build/bdist.linux-x86_64/egg/svtools/lmerge.py", line 632, in run_from_args
File "build/bdist.linux-x86_64/egg/svtools/lmerge.py", line 583, in l_cluster_by_line
UnboundLocalError: local variable 'l' referenced before assignment
```

I'm running with:
```
svtools lsort -t $TMPDIR -b 30000 *.vcf.gz | svtools lmerge -i /dev/stdin --sum \
```

I have verified that none of the files are empty. Any ideas?

**Comment by ernfrid** [comment]
I can replicate with either an empty file or a header-only file. You get a normal looking file if you just run lsort and redirect to an intermediate file?

**Comment by abelhj** [comment]
I'm running into the a similar/the same issue trying to sort a batch of
8-column vcfs.  Looks like the issue is the sort pre-pending ;SNAME= to the
chromosome field on every line after the first.  If I add in a dummy FORMAT
field contains GT it seems ok.





merging$ zcat all.sorted.vcf.gz | grep -A 5 "^#CHROM"

#CHROM POS ID REF ALT QUAL FILTER INFO VARIOUS

1 12461057 1_1 N N]10:19828827] 50.91 .
SVTYPE=BND;STRANDS=++:4;CIPOS=-9,8;CIEND=-9,8;CIPOS95=0,0;CIEND95=0,0;SU=4;PE=0;SR=4;PRPOS=3.78597e-15,1.50722e-13,6.00036e-12,2.38879e-10,9.50993e-09,3.78597e-07,1.50722e-05,0.000600036,0.0238879,0.950993,0.0238879,0.000600036,1.50722e-05,3.78597e-07,9.50993e-09,2.38879e-10,6.00036e-12,1.50722e-13;PREND=3.78597e-15,1.50722e-13,6.00036e-12,2.38879e-10,9.50993e-09,3.78597e-07,1.50722e-05,0.000600036,0.0238879,0.950993,0.0238879,0.000600036,1.50722e-05,3.78597e-07,9.50993e-09,2.38879e-10,6.00036e-12,1.50722e-13;SNAME=H_OS-1932-1932:4413_1;EVENT=1;ALG=PROD;MATEID=1_2

;SNAME=1 12461057 1_1 N N]10:19828827] 67.59 .
SVTYPE=BND;STRANDS=++:4;CIPOS=-9,8;CIEND=-9,8;CIPOS95=0,0;CIEND95=0,0;SU=4;PE=0;SR=4;PRPOS=3.78597e-15,1.50722e-13,6.00036e-12,2.38879e-10,9.50993e-09,3.78597e-07,1.50722e-05,0.000600036,0.0238879,0.950993,0.0238879,0.000600036,1.50722e-05,3.78597e-07,9.50993e-09,2.38879e-10,6.00036e-12,1.50722e-13;PREND=3.78597e-15,1.50722e-13,6.00036e-12,2.38879e-10,9.50993e-09,3.78597e-07,1.50722e-05,0.000600036,0.0238879,0.950993,0.0238879,0.000600036,1.50722e-05,3.78597e-07,9.50993e-09,2.38879e-10,6.00036e-12,1.50722e-13;SNAME=H_OY-FR97_128-FR97_128:4596_1;EVENT=1;ALG=PROD;MATEID=1_2

;SNAME=1 13454888 2_1 N N]10:3972571] 42.10 .
SVTYPE=BND;STRANDS=++:4;IMPRECISE;CIPOS=-10,530;CIEND=-10,373;CIPOS95=-1,185;CIEND95=-2,113;SU=4;PE=4;SR=0;PRPOS=6.59278e-09,1.0448e-07,6.59114e-07,4.15793e-06,2.62294e-05,6.58705e-05,0.000165413,0.000415381,0.00104306,0.00261923,0.00657692,0.00657458,0.00657154,0.00656868,0.00656591,0.0065634,0.00656029,0.00655726,0.00655382,0.00655054,0.00654741,0.00654437,0.0065411,0.006537

**Comment by brentp** [comment]
In my case, it seems I was at least getting this error when using stdin or a compressed file (there may be other problems, but I've found that to be one of them). It would be nice if lmerge detected gzip and used gzip.GzipFile since these files get quite large with dozens of samples.

**Comment by ernfrid** [comment]
Lmerge is one of the few subcommands that doesn't accept gzipped input at this point. I've added an issue to add this feature.

However, I'm a bit puzzled by your issues with reading from stdin. Using the test data in the repo, I was able to mimic your command-line with gzipped input into lsort streaming into lmerge on stdin and didn't see any errors. However, it's possible there is a bug elsewhere, perhaps with larger or more numerous input files?

If you are able to provide any additional information that might shed some light on what's wrong then that would be helpful.
