### ISSUE TITLE
Better handling of cnvnator copynumber value of -1

### ISSUE THREAD

**Issue by ernfrid** [hall-lab/svtools#227]
We occasionally observed this in the past and decided to simply die when it happens. This is likely to be unacceptable. Figure out what this value means, determine a better strategy and deploy.

**Comment by ernfrid** [comment]
Opened https://github.com/abyzovlab/CNVnator/issues/83

**Comment by ernfrid** [comment]
Should this still require an error message. The current error message is terrible. The variant id is reported and it's not clear that this is the idea. The number of the line in the coordinates file is reported "at coordinate {1}" which clearly not a coordinate but instead a line number. SHAME!!!

**Comment by ernfrid** [comment]
Changes here may also affect the behavior of the classifier. For example, if we switch to using null values for CN in this case, will the classifier handle them properly?

**Comment by pmonnahan** [comment]
Curious if there has been any updates on this issue.  I'm currently getting this error message for about 1/3 of my samples.  All of these samples are failing at the same variant position, which seems to be the first non-interchromosomal event.  Is it still the belief that the error is indicative of a bad sample?  

I've mapped all of my samples to 4 different reference genomes, and am running the lumpy/svtools pipeline for all samples for each of the reference genomes.  Interestingly, this CNVnator error is happening disproportionately for samples aligned to one particular reference genome.  This reference dependency would suggest that it isn't simply bad samples, but perhaps depends both on sample quality as well as reference quality?   

Lastly, I gathered that the solution was to set all data as missing for failed samples.  This doesn't seem to be happening for my failed samples.  I tried updating svtools via conda, but looks like everything is up to date.  Has the fix been implemented yet?  Also, does anyone have any insight into how to save the failed samples?

**Comment by ernfrid** [comment]
@pmonnahan - This was implemented, but hasn't made it into an existing release yet. If you can run off the development code then you ought to be able to bring in this change.

I've investigated on a few of our own samples where this was a problem and it was, indeed, an issue with bad samples. I can imagine that the contents of the reference sequence could sufficiently change the read depth distribution such that it causes this problem in cnvnator. However, for our own analyses we have only been using GRCh38DH for our alignments so I have no experience with how different references affect this.

**Comment by pmonnahan** [comment]
@ernfrid - Thanks for getting back on this.  

It turns out it was the window size that was causing the error.  I initially used -w 100 with svtools copynumber.  I inspected the RD histograms using root's TBrowser() as suggested in [abyzovlab/CNVnator#83.](https://github.com/abyzovlab/CNVnator/issues/83), and after fitting the gaussian, I noticed that all failed samples were fit with a negative mean.  I'm guessing this is what is causing the failure in CNVnator.

Rerunning the samples with -w 300 resulted in no errors as well as RD histograms with a positive value for the fitted mean.  However, I'm wondering if I should go back further and rerun speedseq SV with the same window size of 300.  The vcf that I'm using for svtools genotype & copynumber resulted from doing lsort/lmerge on a collection of individual vcfs produced with speedseq sv (default -w 100).  I used the cnvnator_wrapper.py to generate the necessary root files for svtools copynumber to work with -w 300.

Does lmerge (or speedseq sv) rely on the information from CNVnator?

**Comment by ernfrid** [comment]
Neither lmerge nor speedseq sv rely on the information from CNVnator. The CNVnator outputs are only used for svtools copynumber. Be aware that larger window sizes may reduce the accuracy of copynumber estimates for small variants relative to what you might get from samples that were able to be processed using 100bp windows. I'm not suggesting another option or that this is the wrong path forward, I just wanted to ensure that the consequence is clear.

**Comment by pmonnahan** [comment]
Ok great.  Thanks for the info and helpful discussion.
