### ISSUE TITLE
svtools genotype (--cnvnator cnvnator-multi) does not exist

### ISSUE THREAD

**Issue by MehmetGoktay** [hall-lab/svtools#252]
Hi, 

I m trying to get cnvs with svtools using svtools genotype. But the problem is although I have installed speedseq properly I dont have cnvnator-multi executable that is why I can not finalize my analysis with svgenotype.

I have tried to install/compile speedseq several times but still I dont have this exe. 

Is there any possibility to install cnvnator-multi separately then speedseq?

Best,
Mehmet

**Comment by ernfrid** [comment]
If you're able to fully install speedseq and have followed the cnvnator directions here: https://github.com/hall-lab/speedseq#cnvnator then you should have a cnvnator-multi or cnvnator executable inside speedseq's bin directory. 

If I understand you correctly, you've followed the directions and everything seems to work, but that executable is missing?

If I've misunderstood and that executable does exist, then I'd try using the full path to it as the argument to `--cnvnator`. If it doesn't exist then you can certainly compile and install cnvnator-multi separately from speedseq.

**Comment by MehmetGoktay** [comment]
Hi Dave,

Thank you very much for your answer.

Yes you understood correctly, All tools in this pipeline works I also have cnvnator in bin directory of speedseq, But I dont have cnvnator-multi neither in speedseq bin directory nor in cnvnator directory. 

I will give it a try to install cnvnator-multi separately.

Thanks,
Mehmet

**Comment by ernfrid** [comment]
You ought to be able to use cnvnator instead of cnvnator-multi.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ernfrid** [comment]
To be more explicit, you should use whichever cnvnator you've used to generate root files for your genomes. If that is the cnvnator (not cnvnator-multi) from speedseq then you should use that executable as the argument for this step.

cnvnator-multi was/is a custom version of cnvnator that shipped with Speedseq. Speedseq itself has since been updated to use the standard cnvnator from the Abyzov lab.

**Comment by npatel22526** [comment]
Hello Dave, 

Jumping in , Since I've be struggling and thought it could be helpful  for others. 
So I installed newest speedseq and as you mentioned they are using standard cnvnator and generated root files with it. However, in svtools' documentation in specifically says to use "cnvnator-multi" I've been trying to use it for "copynumber" step and was getting error. Finally used standard CNVnator with the step without trouble. 

Thanks,
Nick

**Comment by ernfrid** [comment]
Thanks Nick. I've updated the docs for copynumber to: `path to cnvnator binary for the cnvnator used by speedseq (required)`

This will be in the next release.
