### ISSUE TITLE
SVtype DUP

### ISSUE THREAD

**Issue by sususy** [hall-lab/svtools#258]
Hi,
I am trying to use lumpy to annotate a particular region (~10kb) on chr16. The lumpy output file presented 4 variants (purple lines in Figure.1), three of which are very close to each other. What is interesting is that for the SV types, only one was shown as DUP (dotted purple line in Figure.1), others are all DEL. Also, according to the read depth distributions of 4 variants (Figure 2), all the variants are supposed to be deletions. Is it possible that lumpy mix the types out? What kind of reason could cause that?

Thank you so much for your time and efforts!
Best,
Ye Su
![e77d988aa037cc8ccd3cab3946b8f2de](https://user-images.githubusercontent.com/36517842/40622817-62ffd000-6271-11e8-8668-b1e935070dec.jpg)
![d004a4a33bdc7c8368faf65d129aad36](https://user-images.githubusercontent.com/36517842/40622822-7114691c-6271-11e8-9cc9-7ce60860fea9.jpg)

**Comment by sususy** [comment]
Thanks for you reply! I am not sure I understand correctly. I think you suggested there were both deletions and duplications in this area. But the read depth distribution of the DUP variant shows that it is more likely to be a deletion. The samples with 0/1 genotypes have lower read depths than the ones with 0/0 genotypes. 

![screen shot 2018-06-01 at 10 51 22 am](https://user-images.githubusercontent.com/36517842/40847357-25979128-658a-11e8-9ed0-2359c132a3b3.png)

**Comment by ernfrid** [comment]
Since you're seeing signals from both read orientation and read depth, this is likely to be a real variant. Since the two signals are discordant, a plausible explanation is that the variant you're observing here is more complicated than a simple tandem duplication or deletion. Lumpy doesn't consider the read depth when classifying variants so the duplication classification is solely based on the orientation of discordant reads. 

I think you understand correctly, but keep in mind that you may have overlapping DEL and DUP variants on the same haplotype forming a complex event where the read depth signal indicates the deletion, but the orientations simultaneously indicate a duplication. Other nearby breakpoints may provide additional insight.

**Comment by sususy** [comment]
Glad to know that. Thank you! By the way, how did you get the result of read depth? I think it is different from read count.

**Comment by ernfrid** [comment]
We've typically looked at the copynumber reported by cnvnator in 100 bp windows overlapping the variant region to examine read depth evidence.

**Comment by sususy** [comment]
I see.  But I think the read depths in lumpy output vcf files are much higher than the actual read counts of input bam files. What does the numbers of read depths represent? Average read counts of the variant region? Could you provide any algorithm to help me understand the calculation of read depth in lumpy vcc files?

**Comment by ernfrid** [comment]
Assuming the counts you're referring to are coming after running svtyper then they represent support in a region surrounding the breakpoint. They aren't averages and instead are the count of read pairs supporting either the reference or the variant for each type of evidence evaluated. Since insert size and split read evidence can be present in a single read pair, svtyper may report a single read pair multiple times (once for each class of evidence). Because of this, I would not use the read counts in the output VCF to try to infer copynumber.

**Comment by zjgbz** [comment]
Hi ernfrid,

I also met the similar problems — the read depth is away from our prediction based on the read counts. Thank you for your explanation about how lumpy calculates the read depth. But if it is possible, could you hint me which source code file is for calculating the read depth in this svtools repository? I believed that your explanation and the source codes would be very helpful for a beginner like me. Thank you very much.

**Comment by ernfrid** [comment]
@zjgbz - I'm not familiar with how lumpy itself reports depth and support and was referring to how svtyper calculates and reports variant and reference support. The repository is here: https://github.com/hall-lab/svtyper and I would recommend looking through this file: https://github.com/hall-lab/svtyper/blob/master/svtyper/classic.py
