### ISSUE TITLE
Genotypes all converted to ./.

### ISSUE THREAD

**Issue by gwct** [hall-lab/svtools#277]
Hi all,
I'm working on calling SVs in a sample of 32 primate genomes (~30X coverage each). I've run into a problem in the final step of merging the calls in which the genotypes are all converted to ./.
Here is my workflow so you can pick out any points where I might be making errors:

1. Call SVs with Lumpy for each individual by chromosome separately. I split up by chromosome because each one is taking roughly 20 hours to complete. This results in 32x22 = 704 VCF files.
2. Use svtools lsort to combine the chromosome VCFs for each individual. This results in 32 VCF files.
3. Use svtools lsort to combine the VCFs for each individual. This results in 1 VCF file with ungenotyped calls for all 32 individuals.
4. Use svtyper to genotype the single VCF. This step takes about 300 hours to complete. The reason I am combining them and genotyping all at once is to obtain the statistics such as read depth and AO for all samples and all variants for filtering purposes.
5. Use svtools lmerge to merge the genotyped calls.

After step 4, the genotyped VCF file looks roughly what I would expect it to look like, except that there are multiple lines with the same variant (sometimes with different individuals having different genotypes between lines). After step 5, there is only a single line per variant, but all genotypes and other statistics in the sample columns are ./.:.:.:. ... etc. The only other discrepancy is that after combining chromosomal VCFs in step 2, there are several identical Sample IDs within the file, though I'm not sure that affects anything.

Any guidance would be appreciated. Thank you!
-Gregg Thomas

**Comment by abelhj** [comment]
Hi Gregg,
The typical svtools workflow is described here:
https://github.com/hall-lab/svtools/blob/master/Tutorial.md.

A few comments wrt your approach:

1)  By running Lumpy one chr at a time, you will miss any interchromosomal
events.  On 30X WGS sequence data, Lumpy normally takes a couple of hours
per sample.  We do mask out regions of extremely high copy number (e.g.,
greater than 20 copies on average in a population), by passing these
regions as an exclude list to lumpy.  You may want to consider creating an
exclude list if the lumpy step is taking too long.
2) Lsort is meant to put the variants in order so that they can be merged
by lmerge.  The goal of lmerge is combine variants that are 'the same' in
different samples but not represented in exactly the same way (i.e., the
breakpoints will not necessarily be exactly the same.)  Once the variants
have been merged, you can run svtyper in each sample and this will give you
the statistics (read depth, etc) at each variant in each sample.

Hope this helps.
Haley

**Comment by gwct** [comment]
Just an update: I resolved this issue by following the [tutorial](https://github.com/hall-lab/svtools/blob/master/Tutorial.md) more closely. I also used the `-x` option to exclude repetitive regions when running `lumpy`. This reduced the runtime substantially and allowed me to run all chromosomes for an individual at once, rather than splitting them up.

Thanks.
-Gregg
