### ISSUE TITLE
Running SV-tools across combined VCFs with multiple SV call types

### ISSUE THREAD

**Issue by oalavijeh** [hall-lab/svtools#291]
Dear SVtools team, 

I have "structural VCFs" for >20,000 people, with each file being an aggregate of all SV calls made by Manta and Canvas per patient. These have then been combined into aggregate SV VCFs for cases and controls.

Would SVtools accept these as inputs or would one have to split the aggregated files into individual SV call types e.g. all deletions in one VCF, all duplications etc. 

Many thanks for your time and I look forward to your response. 

Omid

**Comment by apregier** [comment]
I'm not entirely sure what you are wanting to do, but I think you can keep the variant types together.  Note that SVTools does not genotype insertions.  We have also not run it on Canvas output.  If you want to see our whole pipeline, please see: https://github.com/hall-lab/sv-pipeline
We do split out some of the variant types (at the end of merge) to make the genotyping phase more parallel, and because the variant types are handled slightly differently.
