### ISSUE TITLE
does active format list need to be updated here?

### ISSUE THREAD

**Issue by abelhj** [hall-lab/svtools#30]
https://github.com/hall-lab/svtools/blob/master/svtools/vcf/genotype.py#L14

**Comment by ernfrid** [comment]
Not for correct behavior in the current code base because `set_formats` is only called here: https://github.com/hall-lab/svtools/blob/master/svtools/vcf/variant.py#L36-L44

Notice the matching call to `update_active_format_list` at the end. I did this because deferring the construction of that list until the batch of samples was processed seemed like a good idea. 

It does seem like a bit of a booby-trap though...
