### ISSUE TITLE
Off-by-one error in bedpetovcf

### ISSUE THREAD

**Issue by lganel** [hall-lab/svtools#46]
bedpetovcf has an off-by-one error. Calling vcftobedpe followed by bedpetovcf reduces the POS by 1. It seems like this issue is limited to BNDs.
This arose because of commit c1638818018879226ae4fe390353c9a4b7f94c7d, which fixed an off-by-one error in vcftobedpe.

**Comment by ernfrid** [comment]
I just pushed changes that I believe address this, but I would dearly appreciate a double check. Let me know if they look ok.

**Comment by cc2qe** [comment]
I haven't done any testing, but from the code It looks like vcftobedpe is correct for LOB strategy.

bedpetovcf is confusing to me though. It looks like in [adjust_by_cipos and adjust_by_ciend](https://github.com/hall-lab/svtools/blob/master/svtools/bedpe.py#L70) you are already doing the + 1 position bump for BNDs on the negative strand. But then it looks like it is bumped once again in [bedpetovcf.py](https://github.com/hall-lab/svtools/blob/master/svtools/bedpetovcf.py#L92). So it seems like the + 1 bump is happening twice.

If i'm interpreting that correcty, then I don't think it should be bumped in bedpy.py, and we should wait until bedpetovcf.py to bump it, since this is a VCF-specific routine.

**Comment by ernfrid** [comment]
I verified the ALT and POS coordinates of the VCF entries, but didn't look at CIPOS and CIEND. Seems more work will be needed. Thanks for catching this.

**Comment by lganel** [comment]
The POS looks right to me now (VCF -> BEDPE -> VCF doesn't change the POS). I haven't looked into the confidence intervals.

**Comment by ernfrid** [comment]
@cc2qe - Just looked at this again and I see what you were saying. I agree that this is confusing and should be moved.

**Comment by ernfrid** [comment]
@cc2qe and @lganel - I think the last batch of commits I did around BED and VCF conversion should have solved this. Are things looking good from your perspectives?

**Comment by lganel** [comment]
Everything looks good to me!

**Comment by lganel** [comment]
(Sorry, I accidentally hit the close button. I'll leave the decision to you)

**Comment by ernfrid** [comment]
I'll trust ya.
